# Generated by Django 4.1.7 on 2023-03-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('type', models.CharField(max_length=15)),
                ('schedule_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('failed_mail', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('attachment', models.FileField(upload_to='uploads/attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('html', models.FileField(upload_to='uploads/mail/')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('taluk', models.CharField(max_length=200)),
                ('failed', models.IntegerField()),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('media', models.FileField(upload_to='uploads/multimedia/')),
            ],
        ),
    ]
