# Generated by Django 4.1.7 on 2023-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaign_total_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(default='', max_length=225),
        ),
    ]
