# Generated by Django 4.1.7 on 2023-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(max_length=225),
        ),
    ]
