# Generated by Django 4.1.7 on 2023-03-26 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
