# Generated by Django 4.1.7 on 2023-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mailtemplate_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='html',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
