# Generated by Django 4.1.7 on 2023-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_mailtemplate_html_mailtemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
