# Generated by Django 4.1.7 on 2023-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_mailtemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ended_at',
            field=models.DateTimeField(default='2000-01-01T01:01', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='failed_mail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='schedule_at',
            field=models.DateTimeField(default='2000-01-01T01:01', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(default='2000-01-01T01:01', null=True),
        ),
        migrations.AlterField(
            model_name='recipients',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
