# Generated by Django 4.1.7 on 2023-06-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_campaign_ended_at_alter_campaign_failed_mail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignAttachment',
        ),
        migrations.DeleteModel(
            name='MailTemplate',
        ),
        migrations.DeleteModel(
            name='Recipients',
        ),
        migrations.DeleteModel(
            name='TemplateMultimedia',
        ),
    ]
